### ISSUE TITLE
Broken links on probability rules and bayes theorem pages.

### ISSUE THREAD

**Issue by cerbaro** [drvalle1/drvalle1.github.io#1]
* Page: 
  https://drvalle1.github.io/3_Probability_rules.html 
  https://drvalle1.github.io/4_Bayes_theorem.html
* Desc: Back to main menu is redirecting to wrong/broken page.

https://github.com/drvalle1/drvalle1.github.io/blob/990fb86dd991a8eaa7376021270b83a1e9a36da0/3_Probability_rules.html#L387

https://github.com/drvalle1/drvalle1.github.io/blob/990fb86dd991a8eaa7376021270b83a1e9a36da0/4_Bayes_theorem.html#L358

**Comment by drvalle1** [comment]
Thanks for spotting this. It has been fixed.
